let a = ["Chief Complaint",
    "Medical History Diabetes",
    "Medical History Hypertension",
    "Medical History Cardiac Disorder",
    "Medical History Rheumatic Fever",
    "Medical History Epilepsy",
    "Medical History Bleeding Disorders",
    "Medical History Jaundice",
    "Medical History Hepatitis",
    "Medical History Asthma",
    "Medical History Typhoid",
    "Medical History Drug Allergy",
    "Medical History Allergic to L.A Injections",
    "Medical History Anaemia",
    "Medical History Pregnancy",
    "Medical History Menstrual Cycle",
    "Medical History Others",
    "Family History Diabetes",
    "Family History Blood Dyscrasias",
    "Family History Hypertension",
    "Family History Consanguineous Marriage",
    "Family History Others",
    "Clinical Findings",
    "Diagnosis",
    "Prognosis",
    "Investigations",
    "Radiographs",
    "Treatment Plan",
    "Treatment Done",
]
let b = [
    "chiefComplaint",
    "medicalHistorydiabetes",
    "medicalHistoryhypertension",
    "medicalHistorycardiacDisorder",
    "medicalHistoryrheumaticFever",
    "medicalHistoryepilepsy",
    "medicalHistorybleedingDisorders",
    "medicalHistoryjaundice",
    "medicalHistoryhepatitis",
    "medicalHistoryasthma",
    "medicalHistorytyphoid",
    "medicalHistorydrugAllergy",
    "medicalHistoryallergicToLAInjections",
    "medicalHistoryanaemia",
    "medicalHistorypregnancy",
    "medicalHistorymenstrualCycle",
    "medicalHistoryothers",
    "familyHistorydiabetes",
    "familyHistorybloodDyscrasias",
    "familyHistoryhypertension",
    "familyHistoryconsanguineousMarriage",
    "familyHistoryothers",
    "clinicalFindings",
    "diagnosis",
    "prognosis",
    "investigations",
    "radiographs",
    "treatmentPlan",
    "treatmentDone",
]
for (let index = 0; index < a.length; index++) {
    console.log(`<InputControl mt={3}  isReadOnly={user.department !== 'D2'} name="${b[index]}" label="${a[index]}" />`);
}