let a = ["Chief  Complainy  :",
    "MEDICAL HISTORY : ",
    "If Yes, details of the medication :",
    "Allergies if any :",
    "DENTAL HISTORY :",
    "EXTRA0RAL EXAMINATION:",
    "TMJ :",
    "INTRAORAL EXAMINATION:",
    "TEETH FILLED:",
    "TEETH  MISSING :",
    "ROOT TREATED:",
    "OCCLUSION:",
    "OCCLUSION CANINE:",
    "OCCLUSION MOLAR:",
    "OCCLUSION OTHERS:",
    "MISCELLANEOUS:",
    " RADIOGRAPHIC INTERPRETATION :",
    "DIAGNOSIS:",
    "TREATMENT PLAN REMOVABLE PARTIAL DENTURE",
    "TREATMENT PLAN COMPLETE DENTURE",
    "TREATMENT PLAN FIXED PARTIAL DENTURE",
    "TREATMENT PLAN IMPLANT",
    "TREATMENT PLAN ​OTHER",
]
let b = [
    "chiefComplaint",
    "medicalHistory",
    "ifYesDetailsOfTheMedication",
    "allergiesIfAny",
    "dentalHistory",
    "extra0RalExamination",
    "tmj",
    "intraoralExamination",
    "teethFilled",
    "teethMissing",
    "rootTreated",
    "occlusion",
    "occlusionCanine",
    "occlusionMolar",
    "occlusionOthers",
    "miscellaneous",
    "radiographicInterpretation",
    "diagnosis",
    "treatmentPlanRemovablePartialDenture",
    "treatmentPlanCompleteDenture",
    "treatmentPlanFixedPartialDenture",
    "treatmentPlanImplant",
    "treatmentPlanOthers",
]
for (let index = 0; index < a.length; index++) {
    console.log(`<InputControl mt={3}  isReadOnly={user.department !== 'D4'} name="${b[index]}" label="${a[index]}" />`);
}