export const UPDATE_DEPT_DATA_REQUEST = 'UPDATE_DEPT_DATA_REQUEST'
export const UPDATE_DEPT_DATA_SUCCESS = 'UPDATE_DEPT_DATA_SUCCESS'
export const UPDATE_DEPT_DATA_FAIL = 'UPDATE_DEPT_DATA_FAIL'

export const UPDATE_DEPT_DATA_RESET = 'UPDATE_DEPT_DATA_RESET'

export const DELETE_DEPT_DATA_REQUEST = 'DELETE_DEPT_DATA_REQUEST'
export const DELETE_DEPT_DATA_SUCCESS = 'DELETE_DEPT_DATA_SUCCESS'
export const DELETE_DEPT_DATA_FAIL = 'DELETE_DEPT_DATA_FAIL'

export const DELETE_DEPT_DATA_RESET = 'DELETE_DEPT_DATA_RESET'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'