export const UPDATE_DEPT_DATA_REQUEST = 'UPDATE_DEPT_DATA_REQUEST'
export const UPDATE_DEPT_DATA_SUCCESS = 'UPDATE_DEPT_DATA_SUCCESS'
export const UPDATE_DEPT_DATA_FAIL = 'UPDATE_DEPT_DATA_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'