export const ADMIN_PATIENTS_REQUEST = 'ADMIN_PATIENTS_REQUEST'
export const ADMIN_PATIENTS_SUCCESS = 'ADMIN_PATIENTS_SUCCESS'
export const ADMIN_PATIENTS_FAIL = 'ADMIN_PATIENTS_FAIL'

export const PATIENT_REQUEST = 'PATIENT_REQUEST'
export const PATIENT_SUCCESS = 'PATIENT_SUCCESS'
export const PATIENT_FAIL = 'PATIENT_FAIL'

export const NEW_PATIENT_REQUEST = 'NEW_PATIENT_REQUEST'
export const NEW_PATIENT_SUCCESS = 'NEW_PATIENT_SUCCESS'
export const NEW_PATIENT_RESET = 'NEW_PATIENT_RESET'
export const NEW_PATIENT_FAIL = 'NEW_PATIENT_FAIL'

export const DELETE_PATIENT_REQUEST = 'DELETE_PATIENT_REQUEST'
export const DELETE_PATIENT_SUCCESS = 'DELETE_PATIENT_SUCCESS'
export const DELETE_PATIENT_RESET = 'DELETE_PATIENT_RESET'
export const DELETE_PATIENT_FAIL = 'DELETE_PATIENT_FAIL'

export const UPDATE_PATIENT_REQUEST = 'UPDATE_PATIENT_REQUEST'
export const UPDATE_PATIENT_SUCCESS = 'UPDATE_PATIENT_SUCCESS'
export const UPDATE_PATIENT_RESET = 'UPDATE_PATIENT_RESET'
export const UPDATE_PATIENT_FAIL = 'UPDATE_PATIENT_FAIL'

export const PATIENT_DETAILS_REQUEST = 'PATIENT_DETAILS_REQUEST'
export const PATIENT_DETAILS_SUCCESS = 'PATIENT_DETAILS_SUCCESS'
export const PATIENT_DETAILS_FAIL = 'PATIENT_DETAILS_FAIL'
export const PATIENT_RESET = 'PATIENT_RESET'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'