name: Sathyabama Dental Pipeline
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      
      - name: Install dependencies in Frontend
        run: cd frontend && npm install

      - name: Build the Frontend
        run: cd frontend && npm run build
      
      - name: Save Frontend Build to Backend
        run: cp -a frontend/build/. nestjs-backend/client

      - name: Push to Heroku
        run: cd nestjs-backend && git push -f https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git origin/master:master
